import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.76.1";
import * as bcrypt from "https://deno.land/x/bcrypt@v0.4.1/mod.ts";
import { Resend } from "npm:resend@2.0.0";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface SignupRequest {
  email: string;
  password: string;
  restaurantName: string;
  ownerName: string;
  phone?: string;
  businessType?: string;
}

// Generate random 5-digit PIN
function generateRandomPin(): string {
  return Math.floor(10000 + Math.random() * 90000).toString();
}

// Validate email format
function isValidEmail(email: string): boolean {
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  return emailRegex.test(email);
}

// Validate password strength
function isValidPassword(password: string): boolean {
  return password.length >= 8;
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );

    const body: SignupRequest = await req.json();
    const { email, password, restaurantName, ownerName, phone, businessType } = body;

    // Validate required fields
    if (!email || !password || !restaurantName || !ownerName) {
      return new Response(
        JSON.stringify({ 
          success: false, 
          error: 'Missing required fields: email, password, restaurantName, ownerName' 
        }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 400 }
      );
    }

    // Validate email format
    if (!isValidEmail(email)) {
      return new Response(
        JSON.stringify({ success: false, error: 'Invalid email format' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 400 }
      );
    }

    // Validate password strength
    if (!isValidPassword(password)) {
      return new Response(
        JSON.stringify({ success: false, error: 'Password must be at least 8 characters long' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 400 }
      );
    }

    // Check if email already exists in organizations
    const { data: existingOrg, error: checkError } = await supabase
      .from('organizations')
      .select('id')
      .eq('login_email', email)
      .single();

    if (existingOrg) {
      return new Response(
        JSON.stringify({ success: false, error: 'Email already registered' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 409 }
      );
    }

    // Hash password with bcrypt (10 rounds)
    console.log('Hashing password...');
    const salt = await bcrypt.genSalt(10);
    const passwordHash = await bcrypt.hash(password, salt);

    // Create Supabase auth user for owner
    console.log('Creating auth user...');
    const { data: authData, error: authError } = await supabase.auth.admin.createUser({
      email,
      password,
      email_confirm: true,
      user_metadata: {
        name: ownerName,
        role: 'owner'
      }
    });

    if (authError || !authData.user) {
      console.error('Auth user creation failed:', authError);
      return new Response(
        JSON.stringify({ success: false, error: `Failed to create user: ${authError?.message}` }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 500 }
      );
    }

    const userId = authData.user.id;
    let organizationId: string | null = null;
    let branchId: string | null = null;
    let employeeId: string | null = null;

    try {
      // Create organization record (slug auto-generated by trigger)
      console.log('Creating organization...');
      const { data: orgData, error: orgError } = await supabase
        .from('organizations')
        .insert({
          name: restaurantName,
          owner_id: userId,
          login_email: email,
          login_password_hash: passwordHash,
          phone,
          business_type: businessType || 'restaurant',
          is_active: true,
          onboarding_completed: false,
          primary_color: '#8B5CF6',
          accent_color: '#10B981'
        })
        .select('id, slug')
        .single();

      if (orgError || !orgData) {
        throw new Error(`Organization creation failed: ${orgError?.message}`);
      }

      organizationId = orgData.id;
      const slug = orgData.slug;
      console.log(`Organization created: ${organizationId}, slug: ${slug}`);

      // Create default "Main Branch"
      console.log('Creating default branch...');
      const { data: branchData, error: branchError } = await supabase
        .from('branches')
        .insert({
          organization_id: organizationId,
          name: 'Main Branch',
          code: 'MAIN',
          active: true,
          timezone: 'Asia/Kuala_Lumpur'
        })
        .select('id')
        .single();

      if (branchError || !branchData) {
        throw new Error(`Branch creation failed: ${branchError?.message}`);
      }

      branchId = branchData.id;
      console.log(`Branch created: ${branchId}`);

      // Generate random 5-digit PIN for owner
      const defaultPin = generateRandomPin();
      const pinSalt = await bcrypt.genSalt(10);
      const hashedPin = await bcrypt.hash(defaultPin, pinSalt);

      // Create owner employee record
      console.log('Creating owner employee record...');
      const { data: empData, error: empError } = await supabase
        .from('employees')
        .insert({
          name: ownerName,
          email,
          phone,
          role: 'owner',
          pin: hashedPin,
          branch_id: branchId,
          auth_user_id: userId,
          active: true
        })
        .select('id')
        .single();

      if (empError || !empData) {
        throw new Error(`Employee creation failed: ${empError?.message}`);
      }

      employeeId = empData.id;
      console.log(`Employee created: ${employeeId}`);

      // Create user_roles entry
      console.log('Creating user role...');
      const { error: roleError } = await supabase
        .from('user_roles')
        .insert({
          user_id: userId,
          role: 'owner',
          employee_id: employeeId
        });

      if (roleError) {
        throw new Error(`User role creation failed: ${roleError.message}`);
      }

      // Generate setup token (JWT) for wizard
      const { data: sessionData, error: sessionError } = await supabase.auth.admin.generateLink({
        type: 'magiclink',
        email,
        options: {
          redirectTo: `${Deno.env.get('SUPABASE_URL')}/auth/v1/verify`
        }
      });

      if (sessionError) {
        console.warn('Setup token generation failed:', sessionError);
      }

      console.log('Organization signup completed successfully');

      // Send welcome email with Resend
      try {
        const resend = new Resend(Deno.env.get('RESEND_API_KEY'));
        
        const emailHtml = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; }
    .container { max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: linear-gradient(135deg, #8B5CF6 0%, #10B981 100%); color: white; padding: 30px; text-align: center; border-radius: 8px 8px 0 0; }
    .content { background: #f9fafb; padding: 30px; border-radius: 0 0 8px 8px; }
    .pin-box { background: white; border: 2px solid #8B5CF6; padding: 20px; text-align: center; font-size: 24px; font-weight: bold; margin: 20px 0; border-radius: 8px; }
    .info-box { background: white; padding: 15px; border-radius: 8px; margin: 15px 0; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>Welcome to ZeniPOS!</h1>
    </div>
    <div class="content">
      <h2>Hi ${ownerName},</h2>
      <p>Your organization <strong>${restaurantName}</strong> has been successfully registered!</p>
      
      <div class="info-box">
        <p><strong>Login Email:</strong> ${email}</p>
        <p><strong>Organization Slug:</strong> ${slug}</p>
        <p><strong>Restaurant Type:</strong> ${businessType || 'restaurant'}</p>
      </div>
      
      <p><strong>Your Owner PIN for POS access:</strong></p>
      <div class="pin-box">${defaultPin}</div>
      
      <p style="color: #dc2626;"><strong>⚠️ Important:</strong> Please keep this PIN secure and change it after your first login.</p>
      
      <p><strong>Next steps:</strong></p>
      <ol>
        <li>Login at your organization portal</li>
        <li>Use your email and password to access the organization</li>
        <li>Use your PIN to access the POS system</li>
        <li>Complete any remaining setup in the dashboard</li>
      </ol>
      
      <p>If you need help, contact our support team.</p>
      
      <p style="margin-top: 30px; color: #6b7280;">
        Best regards,<br>
        The ZeniPOS Team
      </p>
    </div>
  </div>
</body>
</html>
`;

        await resend.emails.send({
          from: 'ZeniPOS <onboarding@resend.dev>',
          to: [email],
          subject: `Welcome to ZeniPOS - Your PIN: ${defaultPin}`,
          html: emailHtml,
        });

        console.log('Welcome email sent successfully to:', email);
      } catch (emailError) {
        console.error('Failed to send welcome email:', emailError);
        // Don't fail the registration if email fails
      }

      return new Response(
        JSON.stringify({
          success: true,
          organizationId,
          slug,
          setupToken: sessionData?.properties?.action_link || null,
          message: 'Organization created successfully',
          defaultPin // Return PIN for owner (should be sent via email in production)
        }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 201 }
      );

    } catch (rollbackError: any) {
      // Rollback: Delete created records
      console.error('Signup failed, rolling back...', rollbackError.message);

      if (employeeId) {
        await supabase.from('employees').delete().eq('id', employeeId);
      }
      if (branchId) {
        await supabase.from('branches').delete().eq('id', branchId);
      }
      if (organizationId) {
        await supabase.from('organizations').delete().eq('id', organizationId);
      }
      
      // Delete auth user
      await supabase.auth.admin.deleteUser(userId);

      return new Response(
        JSON.stringify({ 
          success: false, 
          error: `Signup failed: ${rollbackError.message}` 
        }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 500 }
      );
    }

  } catch (error: any) {
    console.error('Organization signup error:', error);
    return new Response(
      JSON.stringify({ 
        success: false, 
        error: error.message || 'Internal server error' 
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 500 }
    );
  }
});
