-- Create jarvis_alerts table for proactive monitoring
CREATE TABLE IF NOT EXISTS public.jarvis_alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  type TEXT NOT NULL,
  severity TEXT NOT NULL CHECK (severity IN ('low', 'medium', 'high', 'critical')),
  message TEXT NOT NULL,
  jarvis_analysis TEXT,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'acknowledged', 'resolved')),
  acknowledged_by UUID REFERENCES auth.users(id),
  acknowledged_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_jarvis_alerts_status ON public.jarvis_alerts(status, created_at DESC);
CREATE INDEX idx_jarvis_alerts_type ON public.jarvis_alerts(type, created_at DESC);

-- Enable RLS
ALTER TABLE public.jarvis_alerts ENABLE ROW LEVEL SECURITY;

-- Managers and admins can view all alerts
CREATE POLICY "Managers can view alerts"
  ON public.jarvis_alerts FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles
      WHERE user_roles.user_id = auth.uid()
      AND user_roles.role IN ('admin', 'manager')
    )
  );

-- Managers can acknowledge alerts
CREATE POLICY "Managers can acknowledge alerts"
  ON public.jarvis_alerts FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles
      WHERE user_roles.user_id = auth.uid()
      AND user_roles.role IN ('admin', 'manager')
    )
  );

-- Create generated_reports table for report exports
CREATE TABLE IF NOT EXISTS public.generated_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id),
  type TEXT NOT NULL,
  date_range JSONB NOT NULL,
  data JSONB NOT NULL,
  download_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_generated_reports_user ON public.generated_reports(user_id, created_at DESC);

-- Enable RLS
ALTER TABLE public.generated_reports ENABLE ROW LEVEL SECURITY;

-- Users can view their own reports
CREATE POLICY "Users can view own reports"
  ON public.generated_reports FOR SELECT
  USING (auth.uid() = user_id);

-- Users can insert their own reports
CREATE POLICY "Users can create reports"
  ON public.generated_reports FOR INSERT
  WITH CHECK (auth.uid() = user_id);

COMMENT ON TABLE public.jarvis_alerts IS 'Proactive alerts generated by JARVIS monitoring system';
COMMENT ON TABLE public.generated_reports IS 'Analytical reports generated for export';